name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode private key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 -d > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy using SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key_path: private_key.pem
        port: 22
        script: |
          cd node-js-sample
          git pull
          npm install
          pm2 restart all || pm2 start index.js --name "node-app"
